[links.defaults]
requires_admin = false
target_mode = "directory"
link_mode = "direct"

[[links.entries]]
sources = ["~/armazenamento/.compartilhado/armazenamento/android/downloads"]
target = "~/armazenamento/baixados/android"
target_mode = "exact"

[[links.entries]]
sources = ["~/armazenamento/.compartilhado/sistema"]
target = "~/projetos/pessoal/desktop"
target_mode = "exact"

[[links.entries]]
sources = [
	"~/armazenamento/.compartilhado/projetos",
	"~/armazenamento/.compartilhado/aplicativos",
]
target = "~/"

[[links.entries]]
sources = [
	"~/armazenamento/.compartilhado/*.json",
	"~/armazenamento/.compartilhado/livros",
	"~/armazenamento/.compartilhado/jogos",
	"~/armazenamento/.compartilhado/citações",
	"~/armazenamento/.compartilhado/armazenamento/android",
	"~/armazenamento/.compartilhado/armazenamento/baixados",
	"~/armazenamento/.compartilhado/armazenamento/filosofia",
	"~/armazenamento/.compartilhado/armazenamento/imagens",
	"~/armazenamento/.compartilhado/armazenamento/japonês",
	"~/armazenamento/.compartilhado/armazenamento/línguistica",
	"~/armazenamento/.compartilhado/armazenamento/mext",
	"~/armazenamento/.compartilhado/armazenamento/sudoku",
	"~/armazenamento/.compartilhado/armazenamento/unb",
]
target = "~/armazenamento/"

[[links.entries]]
sources = [
	"~/armazenamento/.compartilhado/sistema/subconfiguração/vscode/projects.json",
]
target = "~/.config/vscode/general/User/globalStorage/alefragnani.project-manager/projects.json"
target_mode = "exact"

[[links.entries]]
sources = ["~/.config/vscode/"]
target = "~/.vscode"
target_mode = "exact"

[[links.entries]]
sources = ["~/armazenamento/.compartilhado/armazenamento/videos"]
target = "~/armazenamento/videos/compartilhado"
target_mode = "exact"

[[links.entries]]
sources = ["~/armazenamento/.compartilhado/armazenamento/entreterimento"]
target = "~/armazenamento/entreterimento/compartilhado"
target_mode = "exact"

[[links.entries]]
requires_admin = true
sources = [
	"./configuração/global/profile",
	"./configuração/global/environment",
	"./configuração/global/locale.conf",
	"./configuração/global/keyd",
]
target = "/etc/"

[[links.entries]]
requires_admin = true
sources = ["./subconfiguração/icons/*"]
target = "/usr/share/icons/"

[[links.entries]]
requires_admin = true
sources = ["./subconfiguração/temas/*"]
target = "/usr/share/themes/"

[[links.entries]]
requires_admin = true
sources = ["./serviços/global/*"]
target = "/run/runit/service/"
link_mode = "contents"

[[links.entries]]
requires_admin = true
sources = ["./subconfiguração/aplicativos/*"]
target = "/usr/share/applications/"

[[links.entries]]
sources = ["./serviços/local/*"]
target = "~/.local/services/"
link_mode = "contents"

[[links.entries]]
sources = ["./configuração/local/*"]
target = "~/.config/"

[[links.entries]]
sources = ["./configuração/cache/sqldeveloper"]
target = "~/.cache/sqldeveloper"
target_mode = "exact"

[[links.entries]]
sources = ["./configuração/cache/sqlcl"]
target = "~/.cache/sqlcl"
target_mode = "exact"

[[links.entries]]
sources = ["~/.cache/sqlcl"]
target = "~/.sqlcl"
target_mode = "exact"

[[links.entries]]
sources = ["./magick.nu"]
target = "~/.config/nushell/scripts/external/magick.nu"
target_mode = "exact"

[[links.entries]]
sources = ["./subconfiguração/fontes"]
target = "~/.local/share/fonts"
target_mode = "exact"

[[links.entries]]
sources = ["./subconfiguração/sioyek"]
target = "~/.local/share/sioyek"
target_mode = "exact"

[[links.entries]]
sources = ["./subconfiguração/nushell"]
target = "~/.local/share/nupm"
target_mode = "exact"

[[links.entries]]
sources = ["./subconfiguração/clipboard"]
target = "~/.cache/cliphist"
target_mode = "exact"

[[links.entries]]
sources = ["./scripts/minimize.nu"]
target = "~/.local/bin/minimize.nu"
target_mode = "exact"

[[links.entries]]
sources = ["./scripts/organize-fav.nu"]
target = "~/.local/bin/organize-fav.nu"
target_mode = "exact"

[[links.entries]]
sources = ["./scripts/xdg-open.nu"]
target = "~/.local/bin/xdg-open.nu"
target_mode = "exact"

[[links.entries]]
sources = ["./scripts/dbus.nu"]
target = "~/.local/bin/dbus.nu"
target_mode = "exact"

[[links.entries]]
sources = ["./scripts/zoom.nu"]
target = "~/.local/bin/zoom.nu"
target_mode = "exact"

[[links.entries]]
sources = ["~/.config/android/"]
target = "~/.android"
target_mode = "exact"

[[links.entries]]
sources = ["./subconfiguração/npm/npmrc"]
target = "~/.config/npm/npmrc"
target_mode = "exact"

# GTK: Only files that can be shared with the current user.
[[links.entries]]
sources = ["./subconfiguração/gtk/2.0/*"]
target = "~/.config/gtk-2.0/"

[[links.entries]]
sources = ["./subconfiguração/gtk/3.0/*"]
target = "~/.config/gtk-3.0/"

[[links.entries]]
sources = ["./subconfiguração/gtk/4.0/*"]
target = "~/.config/gtk-4.0/"

[[packages]]
description = ["cp and mv with progress bar."]
names = ["advcpmv"]

[[packages]]
description = ["Keyboard manager in Japanese."]
names = [
	"fcitx5-configtool",
	"fcitx5-gtk",
	"fcitx5-material-color",
	"fcitx5-qt",
	"fcitx5-mozc-ut",
]

[[packages]]
description = [
	"Qalculate! is an arbitrary precision cross-platform software calculator. It supports complex mathematical operations and concepts such as derivation, integration, data plotting, and unit conversion.",
]
names = ["qalculate"]

[[packages]]
description = ["Sound and music creator."]
names = ["lmms"]

[[packages]]
description = ["To learn a lot of things."]
names = ["anki"]

[[packages]]
description = ["Manage multiple emails."]
names = ["thunderbind"]

[[packages]]
description = ["To manage LBRY and Odysee."]
names = ["lbry-app-bin"]

[[packages]]
description = ["Identify playing song."]
names = ["songrec"]

[[packages]]
description = ["Dynamic Menu for X11."]
names = ["fuzzel"]

[[packages]]
description = ["Common fonts."]
names = [
	"ttf-jetbrains-mono 2.304-1",
	"ttf-jetbrains-mono-nerd 3.1.1-1",
	"ttf-roboto 2.138-4",
	"ttf-opensans 1.101-2",
	"ttf-unifont 15.1.04-1",
]

[[packages]]
description = ["Polkit manager."]
names = ["polkit", "polkit-gnome"]

[[packages]]
description = ["Editor of text."]
names = ["neovim-nightly-bin"]

[[packages]]
description = ["Sound manager."]
names = [
	"libpipewire",
	"pipewire",
	"pipewire-alsa",
	"pipewire-audio",
	"pipewire-pulse",
	"pipewire-session-manager",
]

[[packages]]
description = ["Read source-code of software."]
names = ["tokei"]

[[packages]]
description = ["Download videos from many internet providers."]
names = ["yt-dlp"]

[[packages]]
description = ["Video viewer."]
names = ["mpv"]

[[packages]]
description = ["Telegram Desktop"]
names = ["telegram-desktop"]

[[packages]]
description = ["Image editor."]
names = ["gimp"]

[[packages]]
description = ["Digital art maker."]
names = ["krita"]

[[packages]]
description = ["Image viewer."]
names = ["nsxiv"]

[[packages]]
description = ["Take screenshot."]
names = ["scrot"]

[[packages]]
description = ["File manager."]
names = ["nnn"]

[[packages]]
depends = ["glfw", "clang"]
description = [
	"Zoom-in application for desktop.",
	"Inspired from tscoding/boomer.",
]
names = ["coomer"]

[[packages]]
depends = []
plugins = []
description = ["Record/stream/edit audio."]
names = ["tenacity"]

[[packages]]
depends = []
plugins = ["https://github.com/Jenrykster/animeo"]
description = ["Watch streams."]
names = ["stremio"]

# [[packages]]
# description = ["Selection graphical."]
# names = ["slop"]

# [[packages]]
# description = ["Check spelling mistakes."]
# names = ["aspell"]

#[[packages]]
#section "vale"
#text    "Write better English..."


# [[packages]]
# description = ["Preview-editor for latex."]
# names = ["gummi"]

[[packages]]
names = ["latex-mk", "texlab", "perl-yaml-tiny", "perl-file-homedir"]
description = ["For LaTeX and related document tooling."]

[[packages]]
names = ["paru"]
description = ["Package manager for AUR."]

[[packages]]
names = ["dash", "dashbinsh"]
description = "Faster shell."

[[packages]]
names = ["vscode-json-languageserver"]
description = "JSON language server."

[[packages]]
names = ["vscode-html-languageserver"]
description = "HTML language server."

[[packages]]
names = ["vscode-css-languageserver"]
description = "CSS language server."

[[packages]]
names = ["typescript-language-server"]
description = "Typescript/Javascript language server."

[[packages]]
names = [
	"python-lsp-server",
	"python-lsp-all",
	"python-lsp-black",
	"python-pylint",
	"flake8",
]
description = "Python language server."

[[packages]]
names = ["biome-bin"]
description = "Javascript language server (linter)."

[[packages]]
names = ["typescript"]
description = "Typescript programming language."

[[packages]]
names = ["selectdefaultapplication"]
description = ["Select default application for xdg."]

[[packages]]
names = ["hyprpicker-git"]
description = ["Pick colour of the screen."]

[[packages]]
names = ["foliate", "sioyek"]
description = ["To read PDF, EPUB, among other documents."]

# section ["libreoffice"]
# text    ["To simply convert DOCX files to PDF... "]

# section ["readarr-nightly "]
# text    ["To organise books library and such. "]

[[packages]]
names = ["unifont-jp", "noto-fonts-cjk-jp"]
description = ["For Japanese characters."]

[[packages]]
names = ["ttf-joypixels"]
description = ["For emojis characters."]

[[packages]]
names = ["ncmpcpp"]
description = ["MPD player viewer."]

[[packages]]
names = ["mpd", "mopidy"]
pip = [
	"Mopidy-Listenbrainz",
	"Mopidy-Autoplay",
	"Mopidy-Iris",
	"Mopidy-Listenbrainz",
	"Mopidy-Local",
	"Mopidy-MPD",
	"Mopidy-Scrobbler",
	"Mopidy-Spotify",
	"Mopidy-YouTube",
]
description = ["Music server."]

[[packages]]
names = ["vscode-css-language-server"]
description = ["Language servers for editors."]
